# Spring properties
spring:
  application:
    name: PortalCommonApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta

# HTTP Server
server:
  port: ${PORT:3334}   # HTTP (Tomcat) port

management:
  security:
    enabled: false


---
spring:
  profiles: local
#  datasource:
#    caas:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://45.77.19.223:3306/portaldb
#      username: root
#      password: 'q'
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false

---
spring:
  profiles: dev

datasource:
  caas:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.68.46.219:3306/portaldb
    username: root
    password: '!paas_ta202'
jpa:
  database: postgresql
  show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      strategy: org.hibernate.dialect.MySQL5Dialect
  generate-ddl: false
